### ISSUE TITLE
Getting config.json to work

### ISSUE THREAD

**Issue by Gerii** [silvio/matrix-riot-docker#1]
Hello. I've tried to get this docker container to work with a custom config.json file. But unfortunately, I have failed so far.
When a client accesses my server the config file can't be found it seems.
`[Wed Sep 21 2016 10:51:57 GMT+0000 (UTC)] "GET /config.json" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
[Wed Sep 21 2016 10:51:57 GMT+0000 (UTC)] "GET /config.json" Error (404): "Not found"`
I have attached the full log file.
[riot.txt](https://github.com/silvio/matrix-riot-docker/files/484788/riot.txt)

**Comment by 4311021x** [comment]
I am not sure if this belongs here but it seems like config.json doesn't seem to affect Riot. The file gets served correctly but changing `default_hs_url` doesn't affect Riot. It is still using matrix.org on the home and login page.

**Comment by 4311021x** [comment]
Never mind. I also had issues with login in due to a missing Access-Control-Allow-Origin header. Since Riot and Matrix are running on different sub-domains. Fixing the headers also fixed the default behavior.
