### ISSUE TITLE
would be nice to add more to config

### ISSUE THREAD

**Issue by fwhcat** [silvio/matrix-riot-docker#12]
Considering https://github.com/vector-im/riot-web/blob/master/config.sample.json

It would be nice to know how to define the home server and identity server.
Can these be added to config file ? what's the exact syntax? 

Thanks in advance.

**Comment by silvio** [comment]
Hi @fwhcat,

[This section] explaines all settings for this file.
You only need `default_hs_url` and `default_is_url` to point to your  domain which runs synapse.

[This section]: https://github.com/vector-im/riot-web#configjson
