### ISSUE TITLE
One problem...may be dumb

### ISSUE THREAD

**Issue by Beastea3** [silvio/matrix-riot-docker#16]
I read the docker file and the start shell script, had not found something to config the default server... So, does it mean when i use riot to login to default server, I will connect to a remote server but not the one which deployed in the container? So confused...

**Comment by silvio** [comment]
Hi @Beastea3, riot has a default hs server (matrix.org). you can change this to your own server via `config.json` file. Please see <https://github.com/vector-im/riot-web#configjson>
