### ISSUE TITLE
take over the maintenance 

### ISSUE THREAD

**Issue by andreaspeters** [silvio/matrix-riot-docker#17]
Hi silvio, 
is it also ok for u if we take over the maintenance of you riot repo?

Have a nice day,
Andreas

**Comment by silvio** [comment]
Hi @andreaspeters, this would be good.
Only one thing: be installation friendly regarding old installations. Is this okay for you? I will give you access to this repo and the corresponding docker-hub repo, then ...

Best regards,
Silvio

**Comment by andreaspeters** [comment]
Hi Silvio,
of course its ok for me. We will do it on the same way like the docker-matrix repo. Just know, we didnt change the configuration. To meany peoples use it in production. Dont want to break it. 

Thanks to u Silvio.

Take care,
Andreas
