### ISSUE TITLE
docker-compose with let's encript

### ISSUE THREAD

**Issue by berzas** [silvio/matrix-riot-docker#5]
Hi Silvio,

I would like to use your matrix-riot-docker via `docker-compose.yml`:

    matrix:
     image: silviof/matrix-riot-docker
     container_name: matrix
     restart: always
     environment:
       - VIRTUAL_HOST=domain.org
       - LETSENCRYPT_HOST=domain.org
       - LETSENCRYPT_EMAIL=mail@riseup.net
     volumes:
       - "./data:/data" 

I do that because we are working with docker-compose on all of our containers plus to add some production features as `restart:always` 

When I launch it, is working. But it asks for a `/data/riot.im.conf` as you pointed on your readme.md. But the port is given my my reverse proxy so I don't need it. I don't understand for what is:

    -A 0.0.0.0
    -c 3500

And for ssl I use Let's Encrypt so I don't need that. 
Could you suggest some `riot.im.conf` that fit my needs or explain for what is needed -A and -c parameters?

Thanks in advance

**Comment by silvio** [comment]
thats are option which goes to `http-server`. Here are the help of this server:

```
usage: http-server [path] [options]

options:
  -p           Port to use [8080]
  -a           Address to use [0.0.0.0]
  -d           Show directory listings [true]
  -i           Display autoIndex [true]
  -e --ext     Default file extension if none supplied [none]
  -s --silent  Suppress log messages from output
  --cors[=headers]   Enable CORS via the "Access-Control-Allow-Origin" header
                     Optionally provide CORS headers list separated by commas
  -o [path]    Open browser window after starting the server
  -c           Cache time (max-age) in seconds [3600], e.g. -c10 for 10 seconds.
               To disable caching, use -c-1.
  -U --utc     Use UTC time format in log messages.

  -P --proxy   Fallback proxy if the request cannot be resolved. e.g.: http://someurl.com

  -S --ssl     Enable https.
  -C --cert    Path to ssl cert file (default: cert.pem).
  -K --key     Path to ssl key file (default: key.pem).

  -r --robots  Respond to /robots.txt [User-agent: *\nDisallow: /]
  -h --help    Print this list and exit.
```

I don't know your needs.
I use letsencrypt too via `quay.io/letsencrypt/letsencrypt:latest`. My letsencrypt execution looks so: `/usr/bin/docker run --rm --name "letsencrypt" -v /XXX/letsencrypt/log:/var/log/letsencrypt -v /XXX/letsencrypt/etc:/etc/letsencrypt -v /XXX/letsencrypt/lib:/var/lib/letsencrypt  -v /XXX/letsencrypt/webroot.ini:/webroot.ini -v /XXX/nginx/sites/port80:/webroot quay.io/letsencrypt/letsencrypt:latest --webroot-path "/webroot" -c /webroot.ini -d server.domain.om -d nextserver.domain.com certonly`. This is executed every month via cron job.

Could I help you?

**Comment by silvio** [comment]
No reactions after nearly two months -> closed.
