### ISSUE TITLE
curl: (7) couldn't connect to host

### ISSUE THREAD

**Issue by 4311021x** [silvio/matrix-riot-docker#6]
When I run the container with `docker run -d -v /var/riot:/data silviof/matrix-riot-docker -p 8765`, docker logs tells me:
> Starting up http-server, serving ./ through https
> Available on:
>   https://127.0.0.1:8765
> Hit CTRL-C to stop the server

But `curl https://127.0.0.1:8765` on the docker host returns with
> curl: (7) couldn't connect to host

Can you give me a hint on this? I am using the example riot.im.conf from the readme.

**Comment by silvio** [comment]
you have to put the `-p` before the image name, otherwise no port is forwarded.
`docker run -d -v /var/riot:/data  -p 8765 silviof/matrix-riot-docker`

**Comment by 4311021x** [comment]
I feel so dumb now. Thank you for your quick reply.

**Comment by silvio** [comment]
No problem. you are welcome.
