### ISSUE TITLE
/start.sh: cd: line 34: can't cd to /riot-web/webapp

### ISSUE THREAD

**Issue by ndarilek** [silvio/matrix-riot-docker#7]
The latest version of this image throws this error, no longer serves up Riot, and has been happily serving up its image filesystem. The automated build appears to be groken, and is generating images that don't work.

When I run the latest image, there isn't even a /riot-web/webapp directory, though there is /riot-web.

**Comment by silvio** [comment]
I fix this. Thanks for reporting.

**Comment by silvio** [comment]
Fixed with a7ba09583cc7f0740540b7b1d89b480e0dd2edba.
